{% set name = "llm" %}
{% set version = "0.25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/llm-{{ version }}.tar.gz
  sha256: fe0bbe759cd57c678f82cf525573281f4a954867f45c303a24c573d73fed137a

build:
  noarch: python
  entry_points:
    - llm = llm.cli:cli
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    #- openai >=1.55.3
    - click
    - click-default-group >=1.2.3
    - condense-json >=0.1.2
    - openai >=1.55.3
    - pip
    - pluggy
    - puremagic
    - pydantic >=2.0.0
    - pyreadline3   # [ win ]
    - python-ulid
    - pyyaml
    - setuptools
    - sqlite-migrate >=0.1a2
    - sqlite-utils >=3.37
    # Keep the package noarch but allow for the win only dep
    - __linux  # [linux]
    - __osx    # [osx]
    - __win    # [win]

test:
  imports:
    - llm
    - llm.default_plugins
  commands:
    - pip check
    - llm --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/simonw/llm
  summary: A CLI utility and Python library for interacting with Large Language Models, including OpenAI, PaLM and local models installed on your own machine.
  license_family: APACHE
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://llm.datasette.io/en/stable/
  dev_url: https://github.com/simonw/llm

extra:
  recipe-maintainers:
    - rxm7706
