{% set name = "llm" %}
{% set version = "0.23" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/llm-{{ version }}.tar.gz
  sha256: 552e549a46cbcae6f3414b8f5952d6651a7f8b60b5f09444057a7a52793a6c8e

build:
  noarch: python
  entry_points:
    - llm = llm.cli:cli
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - puremagic
    - python >={{ python_min }}
    - click
    - openai >=1.55.3
    - click-default-group >=1.2.3
    - sqlite-utils >=3.37
    - sqlite-migrate >=0.1a2
    - pydantic >=2.0.0
    - pyyaml
    - pluggy
    - python-ulid
    - setuptools
    - pip
    - pyreadline3  # [win]
    # Keep the package noarch but allow for the win only dep
    - __linux  # [linux]
    - __osx    # [osx]
    - __win    # [win]

test:
  imports:
    - llm
  commands:
    - pip check
    - llm --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/simonw/llm
  summary: A CLI utility and Python library for interacting with Large Language Models, including OpenAI, PaLM and local models installed on your own machine.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
