{% set name = "llm" %}
{% set version = "0.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/llm-{{ version }}.tar.gz
  sha256: 1c4243dea5ec3e7ee50f4fd0b8ccd6475b8f5a6cca2b9aac8270c0e843c0e490

build:
  noarch: python
  entry_points:
    - llm = llm.cli:cli
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - puremagic
    - python >=3.8
    - click
    - openai >=1.0
    - click-default-group >=1.2.3
    - sqlite-utils >=3.37
    - sqlite-migrate >=0.1a2
    - pydantic >=1.10.2
    - pyyaml
    - pluggy
    - python-ulid
    - setuptools
    - pip
    - pyreadline3  # [win]
    # Keep the package noarch but allow for the win only dep
    - __linux  # [linux]
    - __osx    # [osx]
    - __win    # [win]

test:
  imports:
    - llm
  commands:
    - pip check
    - llm --help
  requires:
    - pip

about:
  home: https://github.com/simonw/llm
  summary: A CLI utility and Python library for interacting with Large Language Models, including OpenAI, PaLM and local models installed on your own machine.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
