context:
  name: llm
  version: '0.36'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/llm-${{ version }}.tar.gz
  sha256: e59ad30875a99be2eea0c880543b1ebfe40eea24ae55d4008eb1e12c77964626
  patches:
    # https://github.com/simonw/llm/pull/1180
    - 0001-remove-pip-setuptools.patch

build:
  noarch: python
  python:
    entry_points:
      - llm = llm.cli:cli
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - click
    - condense-json >=1.1
    - openai >3
    - click-default-group >=1.2.3
    - sqlite-utils >=4.0
    - pydantic >=2.0.0
    - pyyaml
    - pluggy
    - python-ulid
    - puremagic
    - if: linux
      then:
        - __linux
    - if: osx
      then:
        - __osx
    - if: win
      then:
        - __win
        - pyreadline3

    - pip
    - setuptools
    - httpx2
    - typing_extensions
tests:
  - python:
      imports:
        - llm
        - llm.default_plugins
      pip_check: true
      python_version: ${{ python_min }}.*
  - script:
      - llm --help

about:
  homepage: https://github.com/simonw/llm
  summary: A CLI utility and Python library for interacting with Large Language Models, including OpenAI, PaLM and local models installed on your own machine.
  license: Apache-2.0
  license_file: LICENSE
  documentation: https://llm.datasette.io/en/stable/
  repository: https://github.com/simonw/llm

extra:
  recipe-maintainers:
    - rxm7706
    - pavelzw
